# Generated by Django 2.0.6 on 2018-06-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0003_auto_20180607_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterPersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Cluster')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Role')),
            ],
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
