# Generated by Django 2.0.6 on 2018-06-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0004_auto_20180607_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='DissertationCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Cluster')),
                ('diss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation')),
            ],
        ),
    ]
