# Generated by Django 2.0.6 on 2018-06-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0006_auto_20180611_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertation',
            name='pub_date',
        ),
    ]
