# Generated by Django 2.0.6 on 2018-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0007_remove_dissertation_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
