# Generated by Django 2.0.6 on 2018-06-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0009_auto_20180612_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertation',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='preference_set',
        ),
    ]
