# Generated by Django 2.0.6 on 2018-06-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0010_auto_20180612_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
