# Generated by Django 2.0.6 on 2018-06-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0012_auto_20180612_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterPersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cluster',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dissertationpreference',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Person'),
        ),
        migrations.AddField(
            model_name='clusterpersonrole',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Cluster'),
        ),
        migrations.AddField(
            model_name='clusterpersonrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Person'),
        ),
        migrations.AddField(
            model_name='clusterpersonrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Role'),
        ),
    ]
