# Generated by Django 2.0.6 on 2018-06-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0013_auto_20180612_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterpersonrole',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='clusterpersonrole',
            name='person',
        ),
        migrations.RemoveField(
            model_name='clusterpersonrole',
            name='role',
        ),
        migrations.DeleteModel(
            name='ClusterPersonRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
